title:              My Blogs
email:              collinccx03@outlook.com
description:        Personal Blog Repository
author:             NEWWORLDCCX
baseurl:            "/"
url:                "https://newworldccx.github.io"

# Social Profiles
twitter_username:   /
github_username:    NEWWORLDCCX
facebook_username:  /
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           GFM
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
