site_name: My Blogs
site_url: https://NEWWORLDCCX.github.io/
repo_url: https://github.com/NEWWORLDCCX/NEWWORLDCCX.github.io
repo_name: Website-git

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
  font:
    code: Cascadia
  logo: images/logo.png
  
use_directory_urls: false

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

nav:
  - Welcome: index.md
  - Notes: 
    - note: notes/note.md
    - Crypto: notes/crypto/crypto.md
  - Blogs:
    - try: blogs/try.md
  - About: about/About.md

extra_javascript:
  - format_more/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - format_more/stylesheets/extra.css

plugins:
  - search
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false
